# Site settings
title: Portfolio for Darren Pearson
description: A Collection of Projects by Darren Pearson
baseurl: "/" # the subpath of your site, e.g. /blog
# url: "https://willianjusten.com.br" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: dpearson100
user_description: Web Developer
user_title: Community College Instructor
email: dpearson100@gmail.com
twitter_username: dpearson100
github_username:  dpearson100


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About Me
    url: /about
  - title: Resume
    url: /resume

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
